### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by abe49** [karelia/ConnectionKit#1]
There is no documentation for this framework. How is one supposed to know how to use it?

**Comment by flemingm** [comment]
what are you trying to do with it?
- It support WebDAV (http, https), SCP, FTP connections.
- It also support droplet for uploading

**Comment by jesper-lindberg** [comment]
How would one go about opening a FTP connection?

**Comment by flemingm** [comment]
Use doxygen  to build documentation html for framework...
http://www.stack.nl/~dimitri/doxygen/download.html#latestsrc

Create a connection object at:

Create a CKConnectionRequest object with location to FTP.

CKAbstractConnection object setup is done with: 
- (id)initWithRequest:(CKConnectionRequest *)request

FTP CKConnectionClient is done with:
- (id)initWithConnection:(CKAbstractConnection *)connection

look at for delegates: 

CKConnectionClient  and CKFTPConnection

also look at:  DropletController.m/.h and it reads a archived CKHost object.

**Comment by jesper-lindberg** [comment]
Thanks, but I'm afraid I'm a bit lost. I've created an instance of CKConnectionRequest and fed it a NSURL. I then pass that to an instance of CKAbstractConnection. What happens next?
