### ISSUE TITLE
Unit tests for SFTP protocol

### ISSUE THREAD

**Issue by samdeane** [karelia/ConnectionKit#17]
Need some tests for the CK2 SFTP implementation

**Comment by mikeabdullah** [comment]
I have some tests uncommitted that run against my local SSH server. The question is, how to avoid checking in your password as part of that?

**Comment by samdeane** [comment]
The way I usually do it is to read the password from NSUserDefaults.

If the value is missing, assert with an error telling the user to run `defaults write otest CK2SFTPTestPassword <pass>"` from the command-line to set the password.

E.g, from CURLProtocolTests:

```
NSString* ftpTest = [[NSUserDefaults standardUserDefaults] objectForKey:@"CURLHandleTestsFTPServer"];
STAssertNotNil(ftpTest, @"need to set a test server address using defaults, e.g: defaults write otest CURLHandleTestsFTPServer \"ftp://user:password@ftp.test.com\"");
```

**Comment by samdeane** [comment]
Alternatively, it might be possible to run another instance of sshd on a custom port as a normal user, then have the test use that. The first answer is probably easier though :)
