### ISSUE TITLE
Reading (remote) file permissions

### ISSUE THREAD

**Issue by gbrhaz** [karelia/ConnectionKit#28]
There are various tests that set NSFilePosixPermissions for both local and FTP, but how do you read the existing ones?

**Comment by mikeabdullah** [comment]
Right now the only route is to do a directory listing of the parent, requesting that specific properties of the resulting URLs be filled in. I'll update the docs with more details soon

Mike.

**Comment by mikeabdullah** [comment]
Also, can I ask why you want to read the file permissions?

**Comment by gbrhaz** [comment]
@mikeabdullah I'm creating a GUI for changing permissions - it'd be nice to have current permissions before the user goes to change them.

**Comment by mikeabdullah** [comment]
Well that's a fair reason for wanting it! I've updated the docs, and implemented `NSFileSecurityKey` support now. Yell if there's more needed.
