### ISSUE TITLE
Use 100 (Continue) for WebDAV connections when server supports it

### ISSUE THREAD

**Issue by mikeabdullah** [karelia/ConnectionKit#30]
Apple tell me this is supported by NSURLConnection since at least OS X 10.7:

> set the "Expect" header to "100-continue"

This needs to be implemented in DAVKit, but I've had to file an issue here since GitHub only supports issues on the root repository it seems.

**Comment by Coneko** [comment]
Github doesn't enable issues on forks by default, I assume because ideally you'd open the issue in the upstream repo you forked from originally, but they can be enabled in a repo's settings.

**Comment by mikeabdullah** [comment]
Ah, didn't realise that. Thanks!
