### ISSUE TITLE
FTP URLs with usernames with an @ in the string

### ISSUE THREAD

**Issue by gbrhaz** [karelia/ConnectionKit#32]
On some of my servers, usernames have an '@' in the field; this is causing problems with a recent merge I just made with Connection Kit. Only problem is, I can't find where the problem originates. All I know is that FTP URLs now include the username in the URL. I guess this could be fixed by encoding any special characters, but I can't even find where the URL is being altered.

**Comment by mikeabdullah** [comment]
I started including user names in URLs vended out by ConnectionKit so as to uniquely identify them. For example the URL `ftp://example.com/test.png` can refer to completely different resources depending on the user that is logged in. Inclusion of user in URLs makes that aspect clear.

The lack of escaping of @ symbols etc. was a bug that I've now fixed. Thanks for spotting it!
