### ISSUE TITLE
Support for renaming items

### ISSUE THREAD

**Issue by mikeabdullah** [karelia/ConnectionKit#34]
Some sort of `-moveItemAtURL:toURL:completionHandler:` method.

For WebDAV, I have no idea if DAVKit already supports this. If not, we'll have to do it ourselves following the spec: http://www.ietf.org/rfc/rfc4918.txt . Either way, make sure to supply `Overwrite: F` to match the Finder's behaviour.

**Comment by mikeabdullah** [comment]
Have implemented the file manager, and API side of things on the `move` branch. Now the individual protocols actually need support it!

**Comment by mikeabdullah** [comment]
FTP's approach is fairly straightforward: http://cr.yp.to/ftp/stor.html

I figure we'll send a request containing a pair of custom commands.

**Comment by mikeabdullah** [comment]
libcurl is documented to accept `rename` as a custom SFTP command. I assume you follow it up with source and destination paths just like the command line.

**Comment by samdeane** [comment]
Ok, for now we're just renaming, not moving, since FTP is a little bit arsey about moving stuff to other directories (it works, but seems to require a relative path).

Have implemented rename for FTP, SFTP and File. Looking at WebDAV next.
