### ISSUE TITLE
Failed to git submodule update --recursive --init

### ISSUE THREAD

**Issue by mmackh** [karelia/ConnectionKit#40]
mimac1:ConnectionKit imariettaone$ git submodule update --recursive --init
Submodule 'CurlHandle' (https://github.com/karelia/CurlHandle.git) registered for path 'CurlHandle'
Submodule 'DAVKit' (https://github.com/karelia/DAVKit.git) registered for path 'DAVKit'
Cloning into 'CurlHandle'...
remote: Counting objects: 3721, done.
remote: Compressing objects: 100% (1064/1064), done.
remote: Total 3721 (delta 2574), reused 3644 (delta 2506)
Receiving objects: 100% (3721/3721), 16.96 MiB | 29 KiB/s, done.
Resolving deltas: 100% (2574/2574), done.
Submodule path 'CurlHandle': checked out 'f1f058668854925949dbb3f0690dd78f7b1cea2c'
Submodule 'CURLHandleSource/Tests/MockServer' (git@github.com:karelia/MockServer.git) registered for path 'CURLHandleSource/Tests/MockServer'
Submodule 'SFTP' (https://github.com/karelia/libssh2_sftp-Cocoa-wrapper.git) registered for path 'SFTP'
Submodule 'c-ares' (git://github.com/bagder/c-ares.git) registered for path 'c-ares'
Submodule 'curl' (git://github.com/karelia/curl.git) registered for path 'curl'
Cloning into 'CURLHandleSource/Tests/MockServer'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:karelia/MockServer.git' into submodule path 'CURLHandleSource/Tests/MockServer' failed
Cloning into 'DAVKit'...
remote: Counting objects: 819, done.
remote: Compressing objects: 100% (389/389), done.
remote: Total 819 (delta 475), reused 746 (delta 410)
Receiving objects: 100% (819/819), 136.38 KiB | 28 KiB/s, done.
Resolving deltas: 100% (475/475), done.
Submodule path 'DAVKit': checked out 'a81c734a20a62caef797663da610cb0cf2bb2ad2'
Submodule 'Tests/MockServer' (git@github.com:karelia/MockServer.git) registered for path 'Tests/MockServer'
Submodule 'Tests/OCUnit2JUnit' (https://github.com/ciryon/OCUnit2JUnit) registered for path 'Tests/OCUnit2JUnit'
Submodule 'iso-8601-date-formatter' (https://github.com/boredzo/iso-8601-date-formatter.git) registered for path 'iso-8601-date-formatter'
Cloning into 'Tests/MockServer'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:karelia/MockServer.git' into submodule path 'Tests/MockServer' failed
Failed to recurse into submodule path 'CurlHandle'
Failed to recurse into submodule path 'DAVKit'

**Comment by mikeabdullah** [comment]
Hey, is this working for you now?

**Comment by mmackh** [comment]
No, it's still not working for me:

```
Submodule 'CURLHandleSource/Tests/MockServer' (git@github.com:karelia/MockServer.git) registered for path 'CURLHandleSource/Tests/MockServer'
Submodule 'SFTP' (https://github.com/karelia/libssh2_sftp-Cocoa-wrapper.git) registered for path 'SFTP'
Submodule 'c-ares' (git://github.com/bagder/c-ares.git) registered for path 'c-ares'
Submodule 'curl' (git://github.com/karelia/curl.git) registered for path 'curl'
Cloning into 'CURLHandleSource/Tests/MockServer'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:karelia/MockServer.git' into submodule path 'CURLHandleSource/Tests/MockServer' failed
Cloning into 'DAVKit'...
remote: Counting objects: 828, done.
remote: Compressing objects: 100% (390/390), done.
remote: Total 828 (delta 454), reused 784 (delta 418)
Receiving objects: 100% (828/828), 148.00 KiB | 44 KiB/s, done.
Resolving deltas: 100% (454/454), done.
Submodule path 'DAVKit': checked out 'cdaa84ebb9411a27a7b8172f4f9efae21b9a12f0'
Submodule 'Tests/MockServer' (git@github.com:karelia/MockServer.git) registered for path 'Tests/MockServer'
Submodule 'Tests/OCUnit2JUnit' (https://github.com/ciryon/OCUnit2JUnit) registered for path 'Tests/OCUnit2JUnit'
Submodule 'iso-8601-date-formatter' (https://github.com/boredzo/iso-8601-date-formatter.git) registered for path 'iso-8601-date-formatter'
Cloning into 'Tests/MockServer'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:karelia/MockServer.git' into submodule path 'Tests/MockServer' failed
Failed to recurse into submodule path 'CurlHandle'
Failed to recurse into submodule path 'DAVKit'
```

**Comment by mikeabdullah** [comment]
See, MockServer is freely available as a public repo, yet it seems GitHub randomly refuses access to some people :(

**Comment by mikeabdullah** [comment]
OK, try something like:
1. Check out the latest `v4.x-beta` branch of CURLHandle
2. Run `git submodule sync`
3. `git submodule update --init`

The sync should tell it to start using the HTTP address for the repo, whereupon cloning it should work for you

**Comment by mmackh** [comment]
Thank you, worked great - is this going to be the default option at some point?

**Comment by mmackh** [comment]
Just noticed, this is also happening with DAVKit, same error

**Comment by Coneko** [comment]
It's because the submodules are registered with their ssh url instead of the https one. This was changed in f9a741bcd9c281d2f23192c5d5580d41ad069b3f for the main ConnectionKit repo, but some of the submodules still have ssh url references.

**Comment by altivec-** [comment]
Same problem here. Tried to resolve dependencies manually, cloning both davkit and curlhandle with git clone, but now Xcode says "ISO8601DateFormatter.h file not found".

**Comment by Coneko** [comment]
DAVKit and CurlHandle themselves have other submodules, so you have to `git submodule update --init --recursive` in them too.

This is fixed in #38 but since that's a pretty big PR it's gonna take a while to review it.

**Comment by mikeabdullah** [comment]
Right, sorry for the delay everybody. I've finally gone through and set all the submodules to use HTTP URLs. If you've checked out the code previously, pull in the latest from the `v2.x-beta` branch, and then this command should bring all the submodules up-to-date:

```
git submodule foreach --recursive 'git submodule sync'
git submodule update --recursive
```

**Comment by lbottoni** [comment]
$ git submodule foreach --recursive 'git submodule sync'
fatal: Not a git repository (or any of the parent directories): .git
