### ISSUE TITLE
Removal of file via SFTP throws error

### ISSUE THREAD

**Issue by fjaeger** [karelia/ConnectionKit#48]
Bugfix:

``` diff

--- ConnectionKit/CK2SFTPProtocol.m
+++ ConnectionKit/CK2SFTPProtocol.m
@@ -148,7 +148,11 @@
                                           // TODO - it would be better if either we could work out ahead of time whether it's a file or folder we're deleting, or failing that, if the deletion retrying happened at the CKFileManager level instead.
                                           error = nil;
                                           break;
-
+                                          
+                                      case LIBSSH2_FX_OK:
+                                          error = nil;
+                                          break;
+                                          
                                       default:
                                           // our default for other failures is generic
                                           error = [self standardCouldntWriteErrorWithUnderlyingError:error];
```

**Comment by mikeabdullah** [comment]
Not sure I understand this one too clearly. Any chance of a pull request, and some explanation of the bug?

**Comment by fjaeger** [comment]
When I try to remove a file from an SFTP server, the current implementation returns an error, even though the file is successfully removed. If I understand your code correctly, then the error comes from the fact that it not only tries to remove a file (which is successful), but also tries to remove a directory of the same name (which obviously fails as there is no such directory)... 
What I am fixing here:

If the CURL response code says "LIBSSH2_FX_OK" (no error), you are still generating an error object and returning that?!

**Comment by mikeabdullah** [comment]
Ah yes, we have some weirdness in the codebase to try and handle the difference between files and directories, but it was never quite finished. I'll swing by for another look at that soon.

**Comment by mikeabdullah** [comment]
Alright, I've committed b7b8d72f2f423bec2f505ce16f4552646cdedcc3 which cleans up the deletion system, and documents its current shortcomings. Does that suit your needs for now?

**Comment by fjaeger** [comment]
Thanks for your work! I will test it in my application scenario tonight and let you know if it fixes my problem.

**Comment by fjaeger** [comment]
Seems to work. Good work!
