### ISSUE TITLE
Failed to git submodule update --recursive --init (again)

### ISSUE THREAD

**Issue by ghost** [karelia/ConnectionKit#50]
I have trouble getting all the submodules. I have seen ticket https://github.com/karelia/ConnectionKit/issues/40, which is similar, but for the libssh2 and openssl submodules. Here is what I get:

[19:12] ConnectionKit > git submodule update --recursive --init
Submodule 'CurlHandle' (https://github.com/karelia/CurlHandle.git) registered for path 'CurlHandle'
Submodule 'DAVKit' (https://github.com/karelia/DAVKit.git) registered for path 'DAVKit'
Cloning into 'CurlHandle'...
remote: Counting objects: 4225, done.
remote: Compressing objects: 100% (1201/1201), done.
remote: Total 4225 (delta 2932), reused 4141 (delta 2858)
Receiving objects: 100% (4225/4225), 19.53 MiB | 231 KiB/s, done.
Resolving deltas: 100% (2932/2932), done.
Submodule path 'CurlHandle': checked out '5f8e07c03878437ffa69479dfaf7c58851309638'
Submodule 'CURLHandleSource/Tests/MockServer' (https://github.com/karelia/MockServer.git) registered for path 'CURLHandleSource/Tests/MockServer'
Submodule 'SFTP' (https://github.com/karelia/libssh2_sftp-Cocoa-wrapper.git) registered for path 'SFTP'
Submodule 'c-ares' (https://github.com/bagder/c-ares.git) registered for path 'c-ares'
Submodule 'curl' (https://github.com/karelia/curl.git) registered for path 'curl'
Cloning into 'CURLHandleSource/Tests/MockServer'...
remote: Counting objects: 1702, done.
remote: Compressing objects: 100% (685/685), done.
remote: Total 1702 (delta 927), reused 1687 (delta 913)
Receiving objects: 100% (1702/1702), 3.10 MiB | 267 KiB/s, done.
Resolving deltas: 100% (927/927), done.
Submodule path 'CURLHandleSource/Tests/MockServer': checked out '038870f1e301ee08542d117ce2c8cd612ce42c00'
Submodule 'UnitTests/OCUnit2JUnit' (https://github.com/ciryon/OCUnit2JUnit) registered for path 'UnitTests/OCUnit2JUnit'
Cloning into 'UnitTests/OCUnit2JUnit'...
remote: Counting objects: 149, done.
remote: Compressing objects: 100% (96/96), done.
remote: Total 149 (delta 52), reused 130 (delta 36)
Receiving objects: 100% (149/149), 60.18 KiB, done.
Resolving deltas: 100% (52/52), done.
Submodule path 'UnitTests/OCUnit2JUnit': checked out 'e5ea527cc036eb6227ddd7989767a889b4656be5'
Cloning into 'SFTP'...
remote: Counting objects: 10743, done.
remote: Compressing objects: 100% (3984/3984), done.
remote: Total 10743 (delta 6417), reused 10696 (delta 6381)
Receiving objects: 100% (10743/10743), 29.71 MiB | 371 KiB/s, done.
Resolving deltas: 100% (6417/6417), done.
Submodule path 'SFTP': checked out 'c628a936d45f8a2f68ad1e771035f55d0b5dd1a9'
Submodule 'libssh2' (git://git.libssh2.org/libssh2.git) registered for path 'libssh2'
Submodule 'openssl' (git://git.openssl.org/openssl.git) registered for path 'openssl'
Cloning into 'libssh2'...
fatal: unable to connect to git.libssh2.org:
git.libssh2.org[0: 212.116.89.126]: errno=Connection refused

**Comment by mikeabdullah** [comment]
Hi, those repos work just fine for me. Since we have no special access or control over `libssh2` etc., your best bet is probably to take it up with those project maintainers to find why you're being denied access.

**Comment by arashabdi** [comment]
The problem was the git port is restricted.
I fixed this with:
git config --global url.https://github.com/.insteadOf git://github.com/
