### ISSUE TITLE
NSURLIsDirectoryKey not being set when using WebDAV

### ISSUE THREAD

**Issue by MrNoodle** [karelia/ConnectionKit#52]
Using -contentsOfDirectoryAtURL:... and it seems the URL returned does not have  NSURLIsDirectoryKey set even though it is requested. Doing -getResourceValue:forKey:error: results in a nil object.

**Comment by mikeabdullah** [comment]
Is this just for WebDAV servers? It looks to me like this protocol is buggy, but the others should work.

**Comment by MrNoodle** [comment]
From my tests, it seems so. Is this something that can't be fixed? Is it expected of all WebDAV servers or is there a quirk with the particular one I am testing against? Is there some other way to determine whether something is a directory (like will -contentsOf.. maybe return nil instead of an empty array)? Connecting to the same server using Finder, it seems to distinguish things ok.

**Comment by mikeabdullah** [comment]
Give the latest a go now; I should have fixed it.

**Comment by MrNoodle** [comment]
That seems to do the trick. Thanks.
