### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by mikeabdullah** [karelia/ConnectionKit#57]
I realised that a stupid typo on my part meant that ConnectionKit 2 up until now has not actually been checking SSH host keys. This is a bit of a security weakness, as it makes it a little (maybe a lot?) easier for someone to impersonate a server and perform a man-in-the-middle attack.

I've fixed that in 96b559b9e269a8c6bbdacab290255b94724aeb64. For clients this might be a surprise as they'll now receive an extra authentication callback.

Additionally, I'm considering modernising the auth callback to match `NSURLSession`'s approach. Something like this:

```
- (void)fileManager:(CK2FileManager *)manager didReceiveChallenge:(NSURLAuthenticationChallenge *)challenge completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition disposition, NSURLCredential *credential))completionHandler;
- (void)fileManager:(CK2FileManager *)manager operation:(id)op didReceiveChallenge:(NSURLAuthenticationChallenge *)challenge completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition disposition, NSURLCredential *credential))completionHandler;
```

That would make CK's implementation a little easier, and going forward should be the API that people come to expect, thanks to `NSURLSession`. Would that be OK by you, @MrNoodle ? Anybody else drastically affected?

**Comment by mikeabdullah** [comment]
Last call for complaints, as I'd really like to get this merged in. @MrNoodle? Anybody else?

**Comment by MrNoodle** [comment]
Fine with me. Are you going to make the changes to CK2OpenPanel as well? Do you want to mirror the same API for its delegate?

**Comment by mikeabdullah** [comment]
Sorry, forgot to say I've got https://github.com/karelia/ConnectionKit/pull/59 open with this. I already made the changes to `CK2OpenPanel`'s API too; you just need to update your code to match, and I figured it only fair to give some warning. Oh, and only the second of the two delegate methods is implemented so far; I may do the first one in future too, but that will be a lot cleaner.
