### ISSUE TITLE
Down/Upload and a Crash in Release Build

### ISSUE THREAD

**Issue by miralem-cebic** [karelia/ConnectionKit#71]
Sorry for my maybe stupid question, but I don't understand this Framework really well :/

I need to Download a file from STFP.
Which method must I use?

And I need to Upload a file to SFTP.
Which method must I use here?

And for booth things I need to have something like a progress, to show the up/download  progress for user.

And there is something strange when I click in Xcode on Product->Archive->Distribute->Export As Application. I export the Application to Desktop. When I'm trying to open the App, it fails.

I click on Report and become this message:

 Crashed Thread:  0

 Exception Type:  EXC_BREAKPOINT (SIGTRAP)
 Exception Codes: 0x0000000000000002, 0x0000000000000000

 Application Specific Information:
 dyld: launch, loading dependent libraries

 Dyld Error Message:
  Library not loaded: @rpath/ConnectionKit.framework/Versions/A/ConnectionKit
  Referenced from: /Users/USER/Desktop/AppName.app/Contents/MacOS/AppName
  Reason: image not found

In Debug Mode (cmd+r in xcode) the App start running without problem.

**Comment by mikeabdullah** [comment]
Presently CK2 doesn't support download of files, only upload. I intend to add it at some point, but it's not a priority as we don't need it in Sandvox.

To upload a file, use `-[CK2FileManager createFileOperationWithURL:…]` or `createFileOperationWithData:…` (it's a lot like `NSURLSession`).

To fix your release build:
- Make sure the ConnectionKit framework is being copied into your app bundle
- You probably then need to specify the app's runtime search paths to include that folder

**Comment by miralem-cebic** [comment]
So when I can't download a file, can I read and edit a file on SFTP which CK2?

**Comment by mikeabdullah** [comment]
Um, that sentence doesn't make sense to me. Can you restate the question, please?

CK2 doesn't support download at present, but it should be relatively easy to get started on it by adding a new method to `CK2Protocol` and its subclasses.
