### ISSUE TITLE
Is anyone using -[CK2FileManager setAttributes:…] in their code?

### ISSUE THREAD

**Issue by mikeabdullah** [karelia/ConnectionKit#78]
I'd like to replace it with a variant that doesn't kick the operation off immediately. But if anyone's using it, I'll keep the existing method and add a new one to go alongside it.

**Comment by MrNoodle** [comment]
All clear for me.

**Comment by mikeabdullah** [comment]
I'm going to be brave and delete it then. Anyone else complain here if it causes you a real headache :smiley:
