### ISSUE TITLE
Support for FTP using SSL in Swift 3?

### ISSUE THREAD

**Issue by shorabhd** [karelia/ConnectionKit#96]
Hey,

Does your package support FTP using SSL? I want to use it in Swift 3.

It would be very helpful if you can let me know how to use it. 

Regards,
Shorabh

**Comment by andypotion** [comment]
I'm not the author of this, but I believe it does support FTP over SSL. I've never tried it with Swift 3 so you'll just have to try it to find out.

**Comment by mikeabdullah** [comment]
Yes, it's supported — both kinds. Have a read of the main page — https://github.com/karelia/ConnectionKit — especially the section on auth for FTP over SSL/TLS

**Comment by shorabhd** [comment]
Hey Thanks for the response.

I am new to Swift and I am not familiar with Objective C. How can I use it
in my Swift 3.0 project?

**Comment by mikeabdullah** [comment]
The same way as you would use any other ObjC library from Swift. We have done nothing special to support Swift so far.

**Comment by shorabhd** [comment]
Sorry I missed. I want to use your code for building an app. But i guess it is for OSX only. 

Do you hope to expand? or do you have an idea on any other code which supports FTP with SSL for iOS?
